# -*- coding: utf-8 -*-
"""Evaluating Rag with RAGAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CAh7gLfmB9R1PMJ6aFS1BffgzgUXkCn

# The code represents component level evaluation of RAG pipeline using RAGAS

**1) Install Dependencies**
"""

!pip install langchain langchain-community langchain-huggingface langchain_groq chromadb pdfminer.six sentence-transformers transformers groq langchain-core
!pip install --upgrade ragas

"""**2) Import necessary packages**"""

import os
from langchain_community.document_loaders import PDFMinerLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from langchain_core.prompts import PromptTemplate
from langchain_community.llms import HuggingFacePipeline
from langchain_core.runnables import RunnableLambda, RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (faithfulness, context_recall, context_precision, answer_correctness)
from ragas.run_config import RunConfig

"""**3) Data Ingestion**"""

Loader = PDFMinerLoader('/content/healthy_heart_disease_prevention.pdf')
doc = Loader.load()

"""**4) Chunking**"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 800,
    chunk_overlap = 100)
chunks = text_splitter.split_documents(doc)

"""**5) View sample chunks**"""

print(chunks[0])
print(chunks[1])

"""**6) View no of chunks**"""

print(len(chunks))

"""**7) Create embeddings**"""

embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')

"""**8) Storing embeddings in ChromaDB**"""

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings)

"""**9) Collection count in ChromaDB**"""

print(vectorstore._collection.count())

"""**10) Inspect vector collection**"""

print(vectorstore._collection.get())

"""**11) Set Retriever for semantic retrieval of document chunks**"""

retriever = vectorstore.as_retriever(search_kwargs={"k":3})

"""**12) Initialise Groq API to access Llama model for text generation**"""

from getpass import getpass
import os

api_key = getpass("Enter your Groq API key: ")
os.environ["GROQ_API_KEY"] = api_key

chat_model = ChatGroq(
    model_name="llama-3.1-8b-instant",
    temperature=0
)

"""**13) Generate custom template**"""

template = """
You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question asked only.
Keep the answer concise and If you don't know the answer, just say that you don't know.
DO NOT provide additional commentary or questions.
Context:
{context}

Question: {question}

Answer:"""

prompt = PromptTemplate(template=template, input_variables=["context", "question"])

output_parser = StrOutputParser()

"""**14) Set RAG pipeline**"""

def rag_with_context(query):
    retrieved_docs = retriever.invoke(query)
    context_texts = [doc.page_content for doc in retrieved_docs]

    formatted_context = "\n\n".join(context_texts)

    answer = (
        prompt
        | chat_model
        | output_parser
    ).invoke({
        "context": formatted_context,
        "question": query
    })

    return answer, context_texts

"""**15) Prepare questions and ground truths**"""

questions = [
    "What types of fats are considered heart healthy, and which fats should be avoided?",
    "How do whole grains help in preventing heart disease?",
    "Why is reducing sodium intake important for heart health?",
    "What are the benefits of including fruits and vegetables in a heart healthy diet?",
    "How does maintaining a healthy weight help prevent heart disease?"
]

ground_truths = [
    "Monounsaturated fats and polyunsaturated fats are heart healthy. Monounsaturated fats lower LDL cholesterol and raise HDL cholesterol. Polyunsaturated fats reduce LDL cholesterol and decrease the risk of heart disease. Trans fats increase LDL cholesterol, lower HDL cholesterol, and contribute to inflammation and plaque buildup.",
    "Whole grains are rich in fiber, which lowers cholesterol, regulates blood sugar, and improves heart health. They reduce the risk of heart disease by improving cholesterol levels, blood pressure, and insulin sensitivity.",
    "Excess sodium contributes to high blood pressure, increasing the risk of heart disease. Reducing sodium lowers blood pressure and reduces strain on the heart.",
    "Fruits and vegetables provide vitamins, minerals, antioxidants, and fiber. They support heart health, lower blood pressure, reduce inflammation, lower cholesterol, and improve blood vessel function.",
    "Maintaining a healthy weight regulates blood pressure, cholesterol, and blood sugar levels, reducing strain on the heart and lowering the risk of cardiovascular disease."
]

"""**16) Collect answers and contexts**"""

answers = []
contexts = []

for query in questions:
    answer, context_texts = rag_with_context(query)
    answers.append(answer)
    contexts.append(context_texts)

answers = [
    a.replace("**", "").replace("\n", " ")
    for a in answers
]

"""**17) Prepare the evaluation dataset**"""

from datasets import Dataset

data = {
    "question": questions,
    "answer": answers,
    "contexts": contexts,
    "ground_truth": ground_truths
}

dataset = Dataset.from_dict(data)

"""**18) Set evaluation runtime configuration**"""

run_config = RunConfig(
    max_workers=1,
    timeout=300
)

"""**19) Define retriever evaluation function**"""

def evaluate_retriever(dataset, chat_model, run_config=None):
    return evaluate(
        dataset=dataset,
        metrics=[
            context_precision,
            context_recall
        ],
        llm=chat_model,
        run_config=run_config
    )

"""**20) Define generator evaluation function**"""

def evaluate_generator(dataset, chat_model, embeddings, run_config=None):
    return evaluate(
        dataset=dataset,
        metrics=[
            faithfulness,
            answer_correctness
        ],
        llm=chat_model,
        embeddings=embeddings,
        run_config=run_config
    )

"""**21) Evaluate retriever performance**"""

retriever_result = evaluate_retriever(
    dataset,
    chat_model,
    run_config
)

retriever_df = retriever_result.to_pandas()

"""**22) Evaluate generator performance**"""

generator_result = evaluate_generator(
    dataset,
    chat_model,
    embeddings,
    run_config
)
generator_df = generator_result.to_pandas()

"""**23) Retriever evaluation results**"""

retriever_df

"""**24) Generator evaluation results**"""

generator_df

"""**25) Analysis**


---
**Retriever Performance**

- Achieved perfect context precision (1.0) across all five questions, indicating that all retrieved chunks were relevant.

- Achieved context recall of 1.0 for four out of five questions, demonstrating strong coverage of required information.

- For the multi-part question on heart-healthy fats, context recall dropped to 0.5, indicating partial retrieval of necessary information.

- The retriever performs strongly for single-topic questions but shows slight limitations when handling multi-aspect queries.



---
**Generator Performance**

- Achieved high faithfulness scores (1.0 for four questions and 0.75 for one), indicating strong grounding and minimal hallucination.

- Demonstrates consistent alignment between generated answers and retrieved context.

- Answer correctness scores ranged from 0.417 to 0.917, reflecting varying degrees of semantic alignment with reference answers.

- Lower correctness scores were observed in multi-aspect question, suggesting partial incompleteness.

- High correctness (0.909–0.917) in most cases indicates strong semantic alignment with reference answers.


---
**Further improvements**

- Increase k to improve recall for multi-part questions and reduce incomplete coverage.

- Refine the prompt to enforce completeness, ensuring the generator  includes all relevant aspects mentioned in the context.

- Adjust chunk size and overlap (slightly larger chunks with higher overlap) to prevent splitting related concepts across chunks.

- Expand the evaluation dataset (20–30 questions) to obtain more stable and statistically meaningful performance metrics.




"""